<a href="https://colab.research.google.com/github/simlakhan/Data-Science-Final-Project/blob/main/NumpyHands_On.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Hands-On

In [5]:
import numpy as np  # Import the NumPy library

# Create a 1D NumPy array containing the squares of numbers from 1 to 5
arr = np.array([x**2 for x in range(1, 6)])

# Print the result
print("arr =", arr)


arr = [ 1  4  9 16 25]


In [7]:
# 2# Write a program to create a 3*3 identity matrix using NumPy

# Create a 3*3 identity matrix
identity_matrix = np.eye(3)

# Print the identity matrix
print("identity_matrix =")
print(identity_matrix)

identity_matrix =
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# 3# Write code to reshape a 1D NumPy array [1,2,3,4,5,6] into a 2D array with 2 rows and 3 columns

# Create the 1D NumPy array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)

# Print the reshaped 2D array
print("reshaped_arr =")
print(reshaped_arr)

reshaped_arr =
[[1 2 3]
 [4 5 6]]


In [13]:
# 4# Create a 3D NumPy array of shape (2,2,3) with random integers between 0 and 10

# Create a 3D NumPy array of shape (2, 2, 3) with random integers between 0 and 10
arr_3d = np.random.randint(0, 10, (2, 2, 3))

# Print the 3D array
print("arr_3d =")
print(arr_3d)

arr_3d =
[[[6 0 7]
  [4 5 0]]

 [[2 6 8]
  [0 3 5]]]


In [14]:
# 5# Given a 1D Numpy array arr = np.array([10, 20, 30, 40, 50]), how would you extract the subarray [20, 30, 40] using slicing?

# Create the 1D NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Extract the subarray [20, 30, 40] using slicing
subarray = arr[1:4]  # Start from index 1, up to but not including index 4

# Print the subarray
print("subarray =", subarray)

subarray = [20 30 40]


In [15]:
# 6# Consider the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]). How would you slice out the second row [4, 5, 6]?

# Create the 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice out the second row [4, 5, 6]
second_row = arr[1, :]  # Use row index 1 and all columns (:) to extract the second row

# Print the second row
print("second_row =", second_row)

second_row = [4 5 6]


In [16]:
# 7# For the 2D array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]). How would you extract the first two columns as a new 2D array?

# Create the 2D NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Extract the first two columns as a new 2D array
first_two_columns = arr[:, :2]  # Select all rows (:) and the first two columns (:2)

# Print the new 2D array
print("first_two_columns =")
print(first_two_columns)

first_two_columns =
[[1 2]
 [4 5]
 [7 8]]


In [17]:
# 8# Given a 3D array arr = np.random.randint(1, 10, (3, 3, 3)), write a code to extract the second 2D slice (i.e., arr[1, :, :]).

# Create a 3D NumPy array with random integers between 1 and 10, with shape (3, 3, 3)
# Create a 3D array with random integers between 1 and 10
arr = np.random.randint(1, 10, (3, 3, 3))

# Extract the second 2D slice
second_2d_slice = arr[1, :, :]

# Print the original array and the slice
print("arr =")
print(arr)
print("\nsecond_2d_slice =")
print(second_2d_slice)

arr =
[[[3 9 2]
  [7 6 9]
  [1 4 6]]

 [[8 8 4]
  [9 5 3]
  [6 9 5]]

 [[7 6 4]
  [4 2 6]
  [8 7 8]]]

second_2d_slice =
[[8 8 4]
 [9 5 3]
 [6 9 5]]


In [18]:
# 9## For the array arr = np.array([10, 20, 30, 40, 50]), how would you slice and reverse the array to get [50, 40, 30, 20, 10]?

# Create the 1D NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Reverse the array using slicing
reversed_arr = arr[::-1]  # The slice notation with -1 reverses the array

# Print the reversed array
print("reversed array:", reversed_arr)

reversed array: [50 40 30 20 10]


In [19]:
# 10## Given two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), write a code to calculate their dot product using NumPy.

# Create the 1D NumPy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculate the dot product using np.dot()
dot_product = np.dot(a, b)

# Print the result
print("dot_product = a @ b", dot_product)

dot_product = a @ b 32
